name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - if: startsWith(matrix.os, 'macos')
      run: brew install bash
    - run:
        git config --global user.email "you@example.com";
        git config --global user.name "Your Name";
    - name: Install git-subrepo
      run: |
        git clone https://github.com/ingydotnet/git-subrepo /tmp/git-subrepo
        source /tmp/git-subrepo/.rc
        echo "/tmp/git-subrepo/lib" >> $GITHUB_PATH
    - run: make test
