name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - if: startsWith(matrix.os, 'macos')
      run: brew install bash
    - name: Install git-subrepo
      run: |
        if ! git subrepo --version > /dev/null 2>&1; then
          git clone https://github.com/ingydotnet/git-subrepo /tmp/git-subrepo
          echo "source /tmp/git-subrepo/.rc" >> ~/.bashrc
          source ~/.bashrc
        fi
    - run:
        git config --global user.email "you@example.com";
        git config --global user.name "Your Name";
    - run: make test
